import { Subscription, Transaction } from './types';

export const POPULAR_SERVICES = [
  { name: 'Netflix', emoji: '🎬', color: '#E50914', category: 'streaming' },
  { name: 'Spotify', emoji: '🎵', color: '#1DB954', category: 'music' },
  { name: 'Disney+', emoji: '✨', color: '#0063E5', category: 'streaming' },
  { name: 'HBO Max', emoji: '📺', color: '#6600FF', category: 'streaming' },
  { name: 'YouTube Premium', emoji: '▶️', color: '#FF0000', category: 'streaming' },
  { name: 'Apple Music', emoji: '🎶', color: '#FC3C44', category: 'music' },
  { name: 'Apple TV+', emoji: '🍎', color: '#555555', category: 'streaming' },
  { name: 'Amazon Prime', emoji: '📦', color: '#FF9900', category: 'streaming' },
  { name: 'Adobe CC', emoji: '🎨', color: '#FF0000', category: 'software' },
  { name: 'Microsoft 365', emoji: '💼', color: '#0078D4', category: 'software' },
  { name: 'Google One', emoji: '☁️', color: '#4285F4', category: 'cloud' },
  { name: 'iCloud', emoji: '🌤️', color: '#147EFB', category: 'cloud' },
  { name: 'Dropbox', emoji: '📁', color: '#0061FF', category: 'cloud' },
  { name: 'PlayStation Plus', emoji: '🎮', color: '#003087', category: 'gaming' },
  { name: 'Xbox Game Pass', emoji: '🕹️', color: '#107C10', category: 'gaming' },
  { name: 'Notion', emoji: '📝', color: '#000000', category: 'software' },
  { name: 'Figma', emoji: '🖌️', color: '#F24E1E', category: 'software' },
  { name: 'GitHub', emoji: '💻', color: '#24292E', category: 'software' },
  { name: 'NordVPN', emoji: '🔒', color: '#4687FF', category: 'software' },
  { name: 'MEO', emoji: '📡', color: '#0099CC', category: 'other' },
  { name: 'NOS', emoji: '📶', color: '#FF6600', category: 'other' },
  { name: 'Vodafone', emoji: '📱', color: '#E60000', category: 'other' },
];

export const CATEGORY_LABELS: Record<string, string> = {
  streaming: 'Streaming',
  music: 'Music',
  software: 'Software',
  gaming: 'Gaming',
  cloud: 'Cloud',
  news: 'News',
  fitness: 'Fitness',
  food: 'Food',
  finance: 'Finance',
  other: 'Other',
};

export const CATEGORY_COLORS: Record<string, string> = {
  streaming: '#7C3AED',
  music: '#10B981',
  software: '#3B82F6',
  gaming: '#F59E0B',
  cloud: '#06B6D4',
  news: '#6B7280',
  fitness: '#EF4444',
  food: '#F97316',
  finance: '#84CC16',
  other: '#8B5CF6',
};

export const DEFAULT_SUBSCRIPTIONS: Subscription[] = [
  {
    id: '1',
    name: 'Netflix',
    amount: 15.99,
    currency: 'EUR',
    billingCycle: 'monthly',
    nextBillingDate: '2026-05-22',
    category: 'streaming',
    color: '#E50914',
    emoji: '🎬',
    active: true,
  },
  {
    id: '2',
    name: 'Spotify',
    amount: 9.99,
    currency: 'EUR',
    billingCycle: 'monthly',
    nextBillingDate: '2026-05-18',
    category: 'music',
    color: '#1DB954',
    emoji: '🎵',
    active: true,
  },
  {
    id: '3',
    name: 'Adobe CC',
    amount: 54.99,
    currency: 'EUR',
    billingCycle: 'monthly',
    nextBillingDate: '2026-06-01',
    category: 'software',
    color: '#FF0000',
    emoji: '🎨',
    active: true,
  },
  {
    id: '4',
    name: 'iCloud',
    amount: 2.99,
    currency: 'EUR',
    billingCycle: 'monthly',
    nextBillingDate: '2026-05-28',
    category: 'cloud',
    color: '#147EFB',
    emoji: '🌤️',
    active: true,
  },
  {
    id: '5',
    name: 'Disney+',
    amount: 8.99,
    currency: 'EUR',
    billingCycle: 'monthly',
    nextBillingDate: '2026-06-05',
    category: 'streaming',
    color: '#0063E5',
    emoji: '✨',
    active: false,
  },
];

export const DEFAULT_TRANSACTIONS: Transaction[] = [
  { id: 't1', description: 'Salary', amount: 1800, type: 'income', category: 'Work', date: '2026-05-01', emoji: '💰' },
  { id: 't2', description: 'Rent', amount: 650, type: 'expense', category: 'Housing', date: '2026-05-02', emoji: '🏠' },
  { id: 't3', description: 'Supermarket', amount: 87.50, type: 'expense', category: 'Food', date: '2026-05-04', emoji: '🛒' },
  { id: 't4', description: 'Electricity', amount: 45.20, type: 'expense', category: 'Utilities', date: '2026-05-06', emoji: '⚡' },
  { id: 't5', description: 'Freelance Design', amount: 350, type: 'income', category: 'Work', date: '2026-05-08', emoji: '💼' },
  { id: 't6', description: 'Restaurant', amount: 32.00, type: 'expense', category: 'Food', date: '2026-05-10', emoji: '🍽️' },
  { id: 't7', description: 'Fuel', amount: 55.00, type: 'expense', category: 'Transport', date: '2026-05-12', emoji: '⛽' },
  { id: 't8', description: 'Pharmacy', amount: 18.90, type: 'expense', category: 'Health', date: '2026-05-13', emoji: '💊' },
];
